name: Daily Repo

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Run eprint_pulls.py
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r eprint/requirements.txt

    - name: Run eprint_pulls.py
      run: python eprint/eprint_pulls.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add eprint/*.json
        git add eprint/log.txt
        git commit -m "auto run"
        git pull
        git push
