name: Daily Isogeny

on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  run-gather-script:
    name: Run isogeny.py
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run isogeny.py
      run: python isogeny/isogeny.py
